app:
  authorities:
    - ROLE_USER
    - ROLE_ADMIN
  properties:
    name: 益淘
    metaKeywords: 益淘,CMS,JAVA
    metaDescription: 益淘介绍
    copyright: "©2016 杭州益淘信息科技有限公司"
    phone: 13588204615
    email: 2844870322@qq.com
spring:
  profiles:
    active: dev
  jersey:
    init:
      jersey.config.server.mvc.templateBasePath.freemarker: /templates/default/
      jersey.config.servlet.filter.staticContentRegex: .*/(images/|img/|css/|js/|fonts/|upload/|favicon.ico).*
      jersey.config.server.mvc.caching.freemarker: true
      jersey.config.server.mediaTypeMappings: "json: application/json, html: text/html"
      jersey.config.disableMoxyJson: true
    type: filter
    filter:
      order: 3
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db/yitao?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 
  jpa:
    database: MYSQL
    generate-ddl: false
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      hibernate.cache.use_query_cache: true
      hibernate.cache.auto_evict_collection_cache: true
      hibernate.cache.use_reference_entries: true
      hibernate.physical_naming_strategy: com.yitao.core.hibernate.HibernatePhysicalNamingStrategy
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: /mnt/java/yitao/lucene
      javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
  data:
    jpa:
      repositories:
        enabled: true
  dao:
    exceptiontranslation:
      enabled: true
  aop:
    auto: true
    proxy-target-class: true
---

spring:
  profiles: dev
  jersey:
    init:
      jersey.config.server.mvc.caching.freemarker: false
  datasource:
    url: jdbc:mysql://127.0.0.1/yitao?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.search.default.directory_provider: ram
--- 

spring:
  profiles: test
  datasource:
    driver-class-name: org.hsqldb.jdbcDriver
    url: jdbc:hsqldb:mem:yitao
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    database: HSQL
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.search.default.directory_provider: ram
